Add PTR record managment for VPS
LTD-Beget/dns pull request #1
Opened 2018-09-11 13:15 UTC by Booggmz

2018-09-11 13:34 UTC, Grey2k requested changes

2018-09-11 13:34 UTC, Grey2k commented on proto/v1/dns.proto
> +            post: "/v1/dns/ptr/set"
host ? 
не REST

2018-09-11 13:39 UTC, Booggmz commented on proto/v1/dns.proto
> +            post: "/v1/dns/ptr/set"
fxd

2018-09-11 14:17 UTC, Grey2k requested changes

2018-09-11 14:17 UTC, Grey2k commented on proto/v1/dns.proto
> +    string host = 1; //FQDN
IP

2018-09-11 14:17 UTC, Grey2k commented on proto/v1/dns.proto
> +    string host = 1; //IP адрес, на который смотрит PTR запись
IP

2018-09-11 14:17 UTC, Grey2k commented on proto/v1/dns.proto
> +            INVALID_IP = 1; //IP указан не верно или не принадлежит пользователю
404

2018-09-11 14:17 UTC, Grey2k commented on proto/v1/dns.proto
> +            INVALID_IP = 2; //IP указан не верно или не принадлежит пользователю
Не корректный owner - 
если IP не найден то 404

2018-09-13 08:14 UTC, Booggmz commented on proto/v1/dns.proto
> +            INVALID_IP = 1; //IP указан не верно или не принадлежит пользователю
всмысле 404? А validationException при констракте NetworkAddress?

2018-09-13 08:20 UTC, Booggmz commented on proto/v1/dns.proto
> +    string host = 1; //FQDN
fxd

2018-09-13 15:13 UTC, Grey2k approved these changes

2018-09-13 15:13 UTC, merged